{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from ganime.model.moving_vae import MovingVAE\n",
    "import tensorflow as tf\n",
    "from ganime.data.base import load_dataset\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-11 04:44:40.405711: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2022-04-11 04:44:42.917688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14256 MB memory:  -> device: 0, name: NVIDIA RTX A4000, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
      "2022-04-11 04:44:42.918781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 14256 MB memory:  -> device: 1, name: NVIDIA RTX A4000, pci bus id: 0000:25:00.0, compute capability: 8.6\n",
      "2022-04-11 04:44:42.919648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 14256 MB memory:  -> device: 2, name: NVIDIA RTX A4000, pci bus id: 0000:41:00.0, compute capability: 8.6\n",
      "2022-04-11 04:44:42.920453: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 14256 MB memory:  -> device: 3, name: NVIDIA RTX A4000, pci bus id: 0000:61:00.0, compute capability: 8.6\n",
      "2022-04-11 04:44:42.921312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:4 with 14256 MB memory:  -> device: 4, name: NVIDIA RTX A4000, pci bus id: 0000:81:00.0, compute capability: 8.6\n",
      "2022-04-11 04:44:42.922139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:5 with 14256 MB memory:  -> device: 5, name: NVIDIA RTX A4000, pci bus id: 0000:a1:00.0, compute capability: 8.6\n",
      "2022-04-11 04:44:42.922962: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:6 with 14256 MB memory:  -> device: 6, name: NVIDIA RTX A4000, pci bus id: 0000:c1:00.0, compute capability: 8.6\n",
      "2022-04-11 04:44:42.923783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:7 with 14256 MB memory:  -> device: 7, name: NVIDIA RTX A4000, pci bus id: 0000:e1:00.0, compute capability: 8.6\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3', '/job:localhost/replica:0/task:0/device:GPU:4', '/job:localhost/replica:0/task:0/device:GPU:5', '/job:localhost/replica:0/task:0/device:GPU:6', '/job:localhost/replica:0/task:0/device:GPU:7')\n"
     ]
    }
   ],
   "source": [
    "strategy = tf.distribute.MirroredStrategy()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-11 04:44:44.127317: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.\n"
     ]
    }
   ],
   "source": [
    "with strategy.scope():\n",
    "    vae = MovingVAE(input_shape=(20, 64, 64, 1))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    }
   ],
   "source": [
    "negloglik = lambda x, rv_x: -rv_x.log_prob(x)\n",
    "\n",
    "with strategy.scope():\n",
    "    vae.compile(optimizer=tf.optimizers.Adam(learning_rate=1e-3),\n",
    "                loss=negloglik)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "data = np.load(\"../../data/mnist_test_seq.npy\")\n",
    "data.shape\n",
    "\n",
    "# We can see that data is of shape (window, n_samples, width, height)\n",
    "# But we want for keras something of shape (n_samples, window, width, height)\n",
    "data = np.moveaxis(data, 0, 1)\n",
    "# Also expand dimensions to have channels at the end (n_samples, window, width, height, channels)\n",
    "data = np.expand_dims(data, axis=-1)\n",
    "data.shape\n",
    "\n",
    "def _preprocess(sample):\n",
    "    image = tf.cast(sample, tf.float32) / 255.  # Scale to unit interval.\n",
    "    image = image < tf.random.uniform(tf.shape(image))   # Randomly binarize.\n",
    "    return image, image\n",
    "\n",
    "train_dataset = (tf.data.Dataset.from_tensor_slices(data[:9000])\n",
    "                 .map(_preprocess)\n",
    "                 .batch(256)\n",
    "                 .prefetch(tf.data.AUTOTUNE)\n",
    "                 .shuffle(int(10e3)))\n",
    "test_dataset = (tf.data.Dataset.from_tensor_slices(data[9000:])\n",
    "                 .map(_preprocess)\n",
    "                 .batch(256)\n",
    "                 .prefetch(tf.data.AUTOTUNE)\n",
    "                 .shuffle(int(10e3)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_dataset, ds_info = load_dataset(\"my_dataset\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-04-11 04:44:57.708760: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:547] The `assert_cardinality` transformation is currently not handled by the auto-shard rewrite and will be removed.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/2\n",
      "INFO:tensorflow:batch_all_reduce: 24 all-reduces with algorithm = nccl, num_packs = 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:batch_all_reduce: 24 all-reduces with algorithm = nccl, num_packs = 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:batch_all_reduce: 24 all-reduces with algorithm = nccl, num_packs = 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:batch_all_reduce: 24 all-reduces with algorithm = nccl, num_packs = 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).\n",
      "2022-04-11 04:45:24.088876: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:390] Filling up shuffle buffer (this may take a while): 34 of 10000\n",
      "2022-04-11 04:45:25.380918: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:415] Shuffle buffer filled.\n",
      "2022-04-11 04:45:25.847045: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101\n",
      "2022-04-11 04:45:26.663134: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101\n",
      "2022-04-11 04:45:27.735687: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101\n",
      "2022-04-11 04:45:28.826325: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101\n",
      "2022-04-11 04:45:29.595240: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.\n",
      "2022-04-11 04:45:29.867849: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101\n",
      "2022-04-11 04:45:31.000405: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101\n",
      "2022-04-11 04:45:32.014117: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101\n",
      "2022-04-11 04:45:32.608211: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8101\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "39/40 [============================>.] - ETA: 0s - loss: 112343.1953"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_2/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_2/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\n9 root error(s) found.\n  (0) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[update_4/AssignAddVariableOp/_769]]\n  (1) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[group_deps/_809]]\n  (2) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[group_deps/_805]]\n  (3) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[group_deps/_797]]\n  (4) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[gradient_tape/replica_1/moving_vae/model/multivariate_normal_tri_l/ActivityRegularizer/kldivergence_loss/tensor_coercible_CONSTRUCTED_AT_replica_1_moving_vae_model_multivariate_normal_tri_l/log_prob/chain_of_shift_of_scale_matvec_linear_operator/inverse_log_det_jacobian/scale_matvec_linear_operator/inverse_log_det_jacobian/LinearOperatorLowerTriangular/log_abs_det/Shape/_367]]\n  (5) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[div_no_nan/ReadVariableOp_5/_702]]\n  (6) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[Adam/Adam/group_deps/_849]]\n  (7) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n  (8) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_2/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_train_function_34966]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Input \u001b[0;32mIn [9]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mvae\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrain_dataset\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m2\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py:67\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     65\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n\u001b[1;32m     66\u001b[0m   filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[0;32m---> 67\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28mNone\u001b[39m\n\u001b[1;32m     68\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     69\u001b[0m   \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/GANime/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py:54\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     52\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     53\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 54\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     55\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     56\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     57\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\nDetected at node 'replica_2/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv' defined at (most recent call last):\n    File \"/usr/lib/python3.8/threading.py\", line 890, in _bootstrap\n      self._bootstrap_inner()\n    File \"/usr/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n      self.run()\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/ganime/model/moving_vae.py\", line 125, in call\n      return self.model(inputs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 220, in __call__\n      distribution, _ = super(DistributionLambda, self).__call__(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 226, in call\n      distribution, value = super(DistributionLambda, self).call(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/keras/layers/core/lambda_layer.py\", line 196, in call\n      result = self.function(inputs, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py\", line 180, in _fn\n      value = distribution._value()  # pylint: disable=protected-access\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/layers/internal/distribution_tensor_coercible.py\", line 215, in _value\n      self._convert_to_tensor_fn(self.tensor_distribution)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/transformed_distribution.py\", line 327, in _call_sample_n\n      x = self._maybe_broadcast_distribution_batch_shape().sample(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1234, in sample\n      return self._call_sample_n(sample_shape, seed, **kwargs)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/distribution.py\", line 1211, in _call_sample_n\n      samples = self._sample_n(\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 298, in _sample_n\n      self._augment_sample_shape(sample_shape), seed=seed)\n    File \"/home/abdalla/GANime/venv/lib/python3.8/site-packages/tensorflow_probability/python/distributions/batch_broadcast.py\", line 236, in _augment_sample_shape\n      [ps.maximum(0, n_batch // underlying_n_batch)]],\nNode: 'replica_2/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv'\n9 root error(s) found.\n  (0) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[update_4/AssignAddVariableOp/_769]]\n  (1) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[group_deps/_809]]\n  (2) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[group_deps/_805]]\n  (3) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[group_deps/_797]]\n  (4) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[gradient_tape/replica_1/moving_vae/model/multivariate_normal_tri_l/ActivityRegularizer/kldivergence_loss/tensor_coercible_CONSTRUCTED_AT_replica_1_moving_vae_model_multivariate_normal_tri_l/log_prob/chain_of_shift_of_scale_matvec_linear_operator/inverse_log_det_jacobian/scale_matvec_linear_operator/inverse_log_det_jacobian/LinearOperatorLowerTriangular/log_abs_det/Shape/_367]]\n  (5) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[div_no_nan/ReadVariableOp_5/_702]]\n  (6) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n\t [[Adam/Adam/group_deps/_849]]\n  (7) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_5/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n  (8) INVALID_ARGUMENT:  Integer division by zero\n\t [[{{node replica_2/moving_vae/model/multivariate_normal_tri_l/tensor_coercible/value/MultivariateNormalTriL/sample/BatchBroadcastSampleNormal/sample/floordiv}}]]\n0 successful operations.\n0 derived errors ignored. [Op:__inference_train_function_34966]"
     ]
    }
   ],
   "source": [
    "vae.fit(train_dataset, epochs=2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "3a8249df8b7044894d7782a831e2faf3db8aed5f9dedc5972f04463fb09cbac8"
  },
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
